<?php $url = $this->getUrl("security/cleaninput/checkForm", array('_secure'=>(bool)Mage::app()->getStore()->isCurrentlySecure())); ?>
<div class="container">
    <div class="col-ms-12">
        <div class="row">
            <form id="check-input" action="<?php echo $url ?>" method="post">
                <div class="col-ms-12">
                    <label>Name</label>
                    <textarea class="required-entry" name="name" cols="50" rows="10" title="Please fil full"></textarea>
                </div>
                <div class="col-ms-12">
                    <button type="submit" class="btn.btn-primary" title="Submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('check-input', true);
    //]]>
</script>